name: arc360menu
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

 
version: 0.1.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  imagebutton: ^0.0.6
  flutter:
    sdk: flutter

  ink_page_indicator: ^0.1.1
  fluttertoast: ^7.1.5
  firebase_core: ^0.4.2+1
  cloud_firestore: ^0.12.11 
  flutter_screenutil: ^1.1.0
 
  moor: ^3.4.0
  moor_ffi: ^0.8.0
  carousel_slider: ^2.3.1
  swipedetector: ^1.2.0
  flutter_swiper: ^1.1.6
  flutter_hamburger_scaffold: ^0.1.0+1
  expansion_card: ^0.1.0
  expansion_tile_card: ^1.1.0
  cupertino_icons: ^1.0.0
  sqflite: ^1.3.2+1
  path_provider:  
  moor_flutter: ^3.1.0

dev_dependencies:
  moor_generator: ^3.4.0
  build_runner: ^1.10.10
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/imgs/
    - assets/data.json
#    - assets/arc360_menu.sql

  uses-material-design: true

  fonts:
    - family: IndieFlower
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf
    - family: Metropolis
      fonts:
        - asset: fonts/metropolis/Metropolis-Black.otf
          weight: 900
        - asset: fonts/metropolis/Metropolis-BlackItalic.otf
          weight: 900
          style: italic
        - asset: fonts/metropolis/Metropolis-Bold.otf
          weight: 700
        - asset: fonts/metropolis/Metropolis-BoldItalic.otf
          weight: 700
          style: italic
        - asset: fonts/metropolis/Metropolis-ExtraBold.otf
          weight: 800
        - asset: fonts/metropolis/Metropolis-ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: fonts/metropolis/Metropolis-ExtraLight.otf
          weight: 200
        - asset: fonts/metropolis/Metropolis-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: fonts/metropolis/Metropolis-Light.otf
          weight: 300
        - asset: fonts/metropolis/Metropolis-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/metropolis/Metropolis-Medium.otf
          weight: 500
        - asset: fonts/metropolis/Metropolis-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/metropolis/Metropolis-Regular.otf
          weight: 400
        - asset: fonts/metropolis/Metropolis-RegularItalic.otf
          weight: 400
          style: italic
        - asset: fonts/metropolis/Metropolis-SemiBold.otf
          weight: 600
        - asset: fonts/metropolis/Metropolis-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/metropolis/Metropolis-Thin.otf
          weight: 100
        - asset: fonts/metropolis/Metropolis-ThinItalic.otf
          weight: 100
          style: italic

